### ISSUE TITLE
Loops and if statements

### ISSUE THREAD

**Issue by fenze** [mini-rose/mocha#20]
Loops design:

```rust
for i in list {
    ...
}


for [k, v] in map {
    ...
}

while cond {

}
```

Logical statements design:

```
(cond) ? {
    ...
} || (cond) {
    ...
} : {

}
```
Where symbols works like '?' == if, '||' == else if, ':' == else.

**Comment by 0verse** [comment]
I like your syntax suggestion! Is if statements supported yet? I try if/elif/else keywords but get unparsable error. Btw I like elif as documented, instead of else if.

**Comment by fenze** [comment]
We're going to combine shell like ifs: [ cond ] && {} || {} and c short if statement: (conf) ? x : y

**Comment by 0verse** [comment]
nice :) implementing a shell language with coffee could be simplier and practical then I guess.

**Comment by fenze** [comment]
I'm working on implement JIT to nxg and make coffee scripts like:

example.ff
```rust
#!/bin/nxg

fn main {
   print("Hello world!")
}

```

cmd: chmod +x example.ff && ./example.ff

**Comment by 0verse** [comment]
this would be great, because one could use coffee rather than bash/zsh to build packages in linux for sure :)

**Comment by bellrise** [comment]
if/else conditions are working as of cf5d30f

**Comment by bellrise** [comment]
For loops ideas moved to #37
